function [ PEPTIDE_IDX, POST_PROB, NUM_PROTEOFORMS] = BPQuant( PROTEIN_SIG, PI_NOT )
%UNTITLED13 Summary of this function goes here
%   Detailed explanation goes here

%% STEP 1:  GENERATE PARAMETERS ASSOCIATED WITH SIGNATURE COUNTS AND PROBABILITIES
[ COUNTS, COUNTS_IDX, PI_PROBS, SIGS ] = Parameter_Trends( PROTEIN_SIG, PI_NOT );

%% STEP 2:  GENERATE THE POSSIBLE PROTEOFORMS
Nu = length(PI_PROBS);
[ P_CONFIGS ] = Proteoform_Configurations( Nu );

%% STEP 3:  GENERATE POSTERIOR PROBABILITY VECTOR AND OUTPUT INDICES
[ POST_PROB, PEPTIDE_IDX, NUM_PROTEOFORMS ] = Generate_Posterior( COUNTS, PI_PROBS, P_CONFIGS, COUNTS_IDX );

       

end

